### ISSUE TITLE
Fix error handling

### ISSUE THREAD

**Issue by AckslD** [StephanieWehner/SimulaQron#27]
We need to catch errors. Right now one can get
`Unhandled erros in Deferred`
which is very hard to debug.
The most simple solution is to make a try/except block around anything that yields a Deferred as follows:
```
try:
    output = yield func_that_returns_deferred()
except Exception as e:
    raise e
```
then the error is at least printed.

**Comment by AckslD** [comment]
@LeonWubben is this also done in virtNode/virtual.py?
We also need to check if there is a function that returns deferred then we should add an error-callback as:
```
d=func_that_returns_deferred()
d.addCallback(func_for_success)
d.addErrBack(func_for_failure)
```

**Comment by LeonWubben** [comment]
I haven't checked virtual.py yet.

Any other files we should check?
There are three usages of addCallback; in startCQC, serverTest (this file is duplicated btw), and in virtual.py
